### PR TITLE
Fix panic if ParseRangeCheck returns nil

### LINKED ISSUE #233: panic in EvaluateThreshold because of unvalidated ParseRangeString return value
ParseRangeString may return NIL on errors, but in EvaluateThreshold this is not checked will lead to a panic

`runtime error: invalid memory address or nil pointer dereference 
goroutine 36 [running]:
runtime/debug.Stack()
	C:/Users/user/go-sdk/go1.21.3/src/runtime/debug/stack.go:24 +0x6b
github.com/atc0005/go-nagios.(*Plugin).ReturnCheckResults(0xc0000c40e0)
	C:/local/progs/go-proj/src/check_hm/vendor/github.com/atc0005/go-nagios/nagios.go:283 +0x305
panic({0x1af6600?, 0x216afd0?})
	C:/Users/user/go-sdk/go1.21.3/src/runtime/panic.go:920 +0x290
github.com/atc0005/go-nagios.(*Plugin).EvaluateThreshold(0xc0000c40e0, {0xc0001f16c0, 0x1, 0x1})
	C:/local/progs/go-proj/src/check_hm/vendor/github.com/atc0005/go-nagios/range.go:153 +0xed
`
First 
https://github.com/atc0005/go-nagios/blob/7a6e9212a75d7cf063a1d0c787c74a4cb847f1a1/range.go#L151-L153
may panic here if CritcalThreshold object is nil

second:
https://github.com/atc0005/go-nagios/blob/7a6e9212a75d7cf063a1d0c787c74a4cb847f1a1/range.go#L160-L164

 may panic here if warningThreshold object is nil

### PR DESCRIPTION
**Pull request by Tommi2Day**
this PR adds checking of nil returns from ParseRangeString in EvaluateThreshold. it returns UNKNOWN state result and an error message.

second I added 2 tests to check this expected behavior

fixes #233, replace #234

### CODE REVIEW

File: range.go [hunk 1]
```diff
@@ -158,6 +164,11 @@ func (p *Plugin) EvaluateThreshold(perfData ...PerformanceData) error {
 
 		if perfData[i].Warn != "" {
 			warningThresholdObject := ParseRangeString(perfData[i].Warn)
+			if warningThresholdObject == nil {
+				err := fmt.Errorf("failed to parse critical range string %s: %w ", perfData[i].Warn, ErrInvalidRangeThreshold)
+				p.ExitStatusCode = StateUNKNOWNExitCode
```
Comment (atc0005) [inline range.go:169]: Did you mean to write `warning` instead?

```diff
-err := fmt.Errorf("failed to parse critical range string %s: %w ", perfData[i].Warn, ErrInvalidRangeThreshold)
+err := fmt.Errorf("failed to parse warning range string %s: %w ", perfData[i].Warn, ErrInvalidRangeThreshold)
```

Comment (Tommi2Day) [reply range.go:169]: grrh, copy/past error. fixed in next commit

**Comment by atc0005** [comment]
Hi @Tommi2Day,

Thanks for your work on this.

Do you feel comfortable squashing the first and third commits together? If not, no problem: we can retain them and merge as-is.

**Comment by Tommi2Day** [comment]
did a rebase and force upload, hopefully it is following your intention

**Comment by atc0005** [comment]
@Tommi2Day Thanks again!
